version: 2.1

jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: 'Build Docker Image'
          command: 'docker build -t pro1 .'
      - run:
          name: 'Save Docker Image'
          command: 'docker save pro1 > pro1.tar'
      - run:
          name: 'Run Docker Container'
          command: |
            docker run -d -e DATABASE_URL=${DATABASE_URL} -p 3000:3000 pro1
            for i in {1..30}; do
              if curl -s http://localhost:3000/health; then
                echo "App is up and running"
                break
              fi
              echo "Waiting for app to start..."
              sleep 5
            done
            docker stop $(docker ps -q)
      - persist_to_workspace:
          root: .
          paths:
            - pro1.tar

  deploy-image:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: 'Load Docker Image'
          command: 'docker load < /tmp/workspace/pro1.tar'
      - run:
          name: 'Install AWS CLI'
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: 'Configure AWS CLI'
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-2
      - run:
          name: 'Login to AWS ECR'
          command: |
            aws ecr get-login-password --region us-east-2 | \
            docker login --username AWS --password-stdin 058264403259.dkr.ecr.us-east-2.amazonaws.com
      - run:
          name: 'Tag Docker Image'
          command: |
            docker tag pro1:latest 058264403259.dkr.ecr.us-east-2.amazonaws.com/pro-1:latest
      - run:
          name: 'Push Docker Image'
          command: |
            docker push 058264403259.dkr.ecr.us-east-2.amazonaws.com/pro-1:latest

  deploy-service:
    machine:
      enabled: true
    steps:
      - run:
          name: 'Install AWS CLI'
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: 'Configure AWS CLI'
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-2
      - run:
          name: 'Deploy Service'
          command: |
            aws ecs update-service --cluster $CLUSTER --service $SERVICE --force-new-deployment

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy-image:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - deploy-service:
          requires:
            - deploy-image
          filters:
            branches:
              only:
                - main
