version: 2.1

jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: "Build Docker Image"
          command: "docker build -t pro1 ."
      - run:
          name: "Save Docker Image"
          command: "docker save pro1 > pro1.tar"
      - run:
          name: "Run Docker Container"
          command: "docker run pro1"
      - persist_to_workspace:
          root: .
          paths:
            - pro1.tar

  deploy-image:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: "Load Docker Image"
          command: "docker load < /workspace/pro1.tar"
      - run:
          name: "Install AWS CLI"
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: "Login to AWS ECR"
          command: |
            aws ecr get-login-password --region us-east-2 | \
            docker login --username AWS --password-stdin 058264403259.dkr.ecr.us-east-2.amazonaws.com
      - run:
          name: "Tag Docker Image"
          command: |
            docker tag pro1:latest 058264403259.dkr.ecr.us-east-2.amazonaws.com/pro1:latest
      - run:
          name: "Push Docker Image"
          command: |
            docker push 058264403259.dkr.ecr.us-east-2.amazonaws.com/pro1:latest

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy-image:
          requires:
            - build
          filters:
            branches:
              only:
                - master